# Generated by Django 5.1.6 on 2025-02-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
