# Generated by Django 5.1.6 on 2025-03-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_book_count_booklibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
