# Generated by Django 5.1.6 on 2025-02-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_books_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='image',
            new_name='cover',
        ),
    ]
